// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DBMigratorVsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDBMigratorVsixPackageString = "ab0b9569-cbba-4f12-93eb-ece9587cef89";
        public static Guid guidDBMigratorVsixPackage = new Guid(guidDBMigratorVsixPackageString);

        public const string guidDBMigratorVsixPackageCmdSetString = "0107146b-f702-4cce-a2d8-8af5eb773b82";
        public static Guid guidDBMigratorVsixPackageCmdSet = new Guid(guidDBMigratorVsixPackageCmdSetString);

        public const string guidImagesString = "ddf6e747-ed71-446f-9da9-98e7514c2ad4";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int DBMigratorWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}