name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build "/home/runner/work/DBMigrator/DBMigrator/DBMigrator.Console/DBMigrator.Console.csproj" --configuration Release
    - name: Test
      run: dotnet test --verbosity normal
    - name: GitHub Releases
      # You may pin to the exact commit or the version.
      # uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f
      uses: fnkr/github-action-ghr@v1.3
