name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build "/home/runner/work/DBMigrator/DBMigrator/DBMigrator.Console/DBMigrator.Console.csproj" --configuration Release
    #- name: Test
    #  run: dotnet test "/home/runner/work/DBMigrator/DBMigrator/DBMigrator.Test/DBMigrator.Test.csproj" --verbosity normal
